display_errors = On
display_startup_errors = On
error_reporting = E_ALL

memory_limit = 512M
upload_max_filesize = 50M
post_max_size = 50M
max_execution_time = 90
max_input_time = 90
date.timezone = Africa/Luanda

; Opcache
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
